version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      major:
        patterns:
          - '*'
        update-types:
          - major
