#!/bin/bash

# shellcheck source=smoke.sh
source smoke.sh

smoke_url_prefix "https://www.theregister.com"
smoke_url_ok "/"
smoke_url_ok "/security"
    smoke_assert_body "Independent news and views for the tech community"
    smoke_assert_body_not_contains "Sorry, this page doesn't exist!"
smoke_url_ok "/2022/08/18/non-existent"
    smoke_assert_body "Independent news and views for the tech community"
    smoke_assert_body_not_contains "Sorry, this page doesn't exist!"
smoke_report